// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WagahighChoices.Kaoruko.Models;

namespace WagahighChoices.Kaoruko.Migrations
{
    [DbContext(typeof(KaorukoDbContext))]
    [Migration("20181020192906_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("WagahighChoices.Kaoruko.Models.SearchResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Choices")
                        .IsRequired();

                    b.Property<int>("Heroine");

                    b.Property<string>("Selections");

                    b.Property<DateTimeOffset>("Timestamp");

                    b.HasKey("Id");

                    b.HasAlternateKey("Choices");

                    b.ToTable("SearchResults");
                });

            modelBuilder.Entity("WagahighChoices.Kaoruko.Models.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("ConnectedAt");

                    b.Property<DateTimeOffset?>("DisconnectedAt");

                    b.HasKey("Id");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("WagahighChoices.Kaoruko.Models.WorkerJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Choices")
                        .IsRequired();

                    b.Property<DateTimeOffset>("EnqueuedAt");

                    b.Property<int?>("SearchResultId");

                    b.Property<int?>("WorkerId");

                    b.HasKey("Id");

                    b.HasAlternateKey("Choices");

                    b.HasIndex("SearchResultId");

                    b.HasIndex("WorkerId");

                    b.ToTable("WorkerJobs");
                });

            modelBuilder.Entity("WagahighChoices.Kaoruko.Models.WorkerLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsError");

                    b.Property<string>("Message")
                        .IsRequired();

                    b.Property<DateTimeOffset>("TimestampOnServer");

                    b.Property<DateTimeOffset>("TimestampOnWorker");

                    b.Property<int>("WorkerId");

                    b.HasKey("Id");

                    b.HasIndex("WorkerId");

                    b.ToTable("WorkerLogs");
                });

            modelBuilder.Entity("WagahighChoices.Kaoruko.Models.WorkerJob", b =>
                {
                    b.HasOne("WagahighChoices.Kaoruko.Models.SearchResult", "SearchResult")
                        .WithMany()
                        .HasForeignKey("SearchResultId");

                    b.HasOne("WagahighChoices.Kaoruko.Models.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId");
                });

            modelBuilder.Entity("WagahighChoices.Kaoruko.Models.WorkerLog", b =>
                {
                    b.HasOne("WagahighChoices.Kaoruko.Models.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
