[package]
name = "toa"
version = "0.1.0"
authors = ["azyobuzin <azyobuzin@users.sourceforge.jp>"]
publish = false

[dependencies]
futures = "0.1.14"
gdi32-sys = "0.2.0"
kernel32-sys = "0.2.2"
time = "0.1.38"
tokio-core = "0.1.9"
user32-sys = "0.2.0"
winapi = "0.2.8"
